CREATE TABLE compileddata (
	country VARCHAR,
	country_code VARCHAR,
	_year VARCHAR,
	population REAL,
	gdp_current_usd REAL,
	total_cancer_cases REAL,
	total_cancer_deaths REAL,
	total_obesity_numbers REAL,
	birth_rate REAL,
	death_rate REAL,
	life_expectency REAL,
	dtp_immunisation REAL,
	measles_immunisation REAL,
	land_area_ha REAL,
	agri_land_pct REAL,
	forest_area_pct REAL,
	cereal_yield_kg_ha REAL,
	cash_crop_yield_kg_ha REAL,
	employment_agri_pct REAL,
	livestock_production_100_index REAL,
	atm_per_100000 REAL,
	borrowers_from_banks REAL,
	broad_money_growth_pct REAL,
	listed_domestic_companies REAL,
	foreign_investment_gdp REAL,
	inflation_pct REAL,
	stocks_traded_pct_gdp REAL,
	total_reserves REAL,
	high_tech_export REAL,
	patent_applications REAL,
	science_publications REAL,
	technology_grants_current_usd REAL

)

SELECT * FROM compileddata